name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches:
      - master

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:

  build:

    runs-on: 'ubuntu-latest'

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: github.event_name != 'push'
      with:
        platforms: arm64
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Check Out Repo Invidious
      uses: actions/checkout@v3
      with:
        repository: "iv-org/invidious"
        ref: 'master'
        path: 'invidious'

    - name: patch invidious main repo
      run: |
        cd invidious
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git am ../patches/*.patch
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push alpine docker image
      id: docker_build_new
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        build-args: |
            release=1
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: rix1337/docker-utube:latest
